package com.merchantsledger.entity;

public enum RoleName {
  SYSTEM_ADMIN,
  SUPPORT_AGENT,
  AUTOMATION_BOT,
  MERCHANT_ADMIN,
  MERCHANT_FINANCE,
  MERCHANT_OPERATIONS,
  MERCHANT_VIEWER,
  WAREHOUSE_MANAGER,
  INVENTORY_AUDITOR,
  PICKER_PACKER,
  RECEIVER_GRN_OPERATOR,
  ADMIN,
  USER,
  MANAGER,
  STAFF
}
